// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: sequencer.proto

package sequencerpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitBatchRequest 批次提交請求
type SubmitBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 批次數據：包含多個序列化的交易
	// 格式：2 (front reserve) + 2 (batch flag) + 4 (txn count) + N*(4 + data) + 4 (seq reserve)
	BatchData     []byte `protobuf:"bytes,1,opt,name=batch_data,json=batchData,proto3" json:"batch_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBatchRequest) Reset() {
	*x = SubmitBatchRequest{}
	mi := &file_sequencer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatchRequest) ProtoMessage() {}

func (x *SubmitBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatchRequest.ProtoReflect.Descriptor instead.
func (*SubmitBatchRequest) Descriptor() ([]byte, []int) {
	return file_sequencer_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitBatchRequest) GetBatchData() []byte {
	if x != nil {
		return x.BatchData
	}
	return nil
}

// SubmitBatchResponse 批次提交響應
type SubmitBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 錯誤信息（如果失敗）
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Sequencer 分配的序號（如果成功）
	SequenceNumber uint32 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitBatchResponse) Reset() {
	*x = SubmitBatchResponse{}
	mi := &file_sequencer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatchResponse) ProtoMessage() {}

func (x *SubmitBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatchResponse.ProtoReflect.Descriptor instead.
func (*SubmitBatchResponse) Descriptor() ([]byte, []int) {
	return file_sequencer_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubmitBatchResponse) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

var File_sequencer_proto protoreflect.FileDescriptor

const file_sequencer_proto_rawDesc = "" +
	"\n" +
	"\x0fsequencer.proto\x12\tsequencer\"3\n" +
	"\x12SubmitBatchRequest\x12\x1d\n" +
	"\n" +
	"batch_data\x18\x01 \x01(\fR\tbatchData\"}\n" +
	"\x13SubmitBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\rR\x0esequenceNumber2`\n" +
	"\x10SequencerService\x12L\n" +
	"\vSubmitBatch\x12\x1d.sequencer.SubmitBatchRequest\x1a\x1e.sequencer.SubmitBatchResponseB)Z'github.com/hyperledger/fabric/sequencerb\x06proto3"

var (
	file_sequencer_proto_rawDescOnce sync.Once
	file_sequencer_proto_rawDescData []byte
)

func file_sequencer_proto_rawDescGZIP() []byte {
	file_sequencer_proto_rawDescOnce.Do(func() {
		file_sequencer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sequencer_proto_rawDesc), len(file_sequencer_proto_rawDesc)))
	})
	return file_sequencer_proto_rawDescData
}

var file_sequencer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sequencer_proto_goTypes = []any{
	(*SubmitBatchRequest)(nil),  // 0: sequencer.SubmitBatchRequest
	(*SubmitBatchResponse)(nil), // 1: sequencer.SubmitBatchResponse
}
var file_sequencer_proto_depIdxs = []int32{
	0, // 0: sequencer.SequencerService.SubmitBatch:input_type -> sequencer.SubmitBatchRequest
	1, // 1: sequencer.SequencerService.SubmitBatch:output_type -> sequencer.SubmitBatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sequencer_proto_init() }
func file_sequencer_proto_init() {
	if File_sequencer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sequencer_proto_rawDesc), len(file_sequencer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sequencer_proto_goTypes,
		DependencyIndexes: file_sequencer_proto_depIdxs,
		MessageInfos:      file_sequencer_proto_msgTypes,
	}.Build()
	File_sequencer_proto = out.File
	file_sequencer_proto_goTypes = nil
	file_sequencer_proto_depIdxs = nil
}
